# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Film Flu Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    if: github.actor == 'dherediat97'
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter pub run build_runner build
        - run: flutter build web
        - uses: bluefireteam/flutter-gh-pages@v8
          with:
            baseHref: /Portfolio/
            targetBranch: gh-pages
            webRenderer: html
