name: portfolio
description: "My Amazing Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  typewritertext: ^3.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/bg_music/first.mp3
    - assets/projects/images
  fonts: 
    - family: Tiny
      fonts:
        - asset: assets/fonts/Tiny-Regular.ttf
    - family: Atma
      fonts:
        - asset: assets/fonts/Atma-Regular.ttf
        - asset: assets/fonts/Atma-Light.ttf
        - asset: assets/fonts/Atma-Medium.ttf
        - asset: assets/fonts/Atma-Regular.ttf
        - asset: assets/fonts/Atma-SemiBold.ttf
        - asset: assets/fonts/Atma-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations