name: portfolio
description: "My Amazing Portfolio"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_music/first.mp3
  fonts:
    - family: Atma
      fonts:
        - asset: assets/fonts/Atma-Regular.ttf
        - asset: assets/fonts/Atma-Light.ttf
        - asset: assets/fonts/Atma-Medium.ttf
        - asset: assets/fonts/Atma-Regular.ttf
        - asset: assets/fonts/Atma-SemiBold.ttf
        - asset: assets/fonts/Atma-Bold.ttf

 